Add homework 2
MaksimGudovich/MaksimGudovich pull request #2
Opened 2021-10-27 12:00 UTC by MaksimGudovich

2021-10-30 13:16 UTC, Delnote requested changes
В идеале в последней работе все сделать в одном тесте либо сделать тесты независимыми. Посмотри по локаторам, если откровенно не к чему зацепиться, то можно идти от названия пунктов меню и т.д.
Часть тест дата можно вынести тем более что они общие со вторым тестом. Можно вынести общие методы.
BeforeClass и BeforeMethod, служебные методы в BaseTest для обоих тестов.

2021-10-30 13:16 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex2/DifferentElementsPageTest.java
> +        WebElement headerServiseButton = webDriver.findElement(By.cssSelector("a.dropdown-toggle :only-child"));
Очень слабый локатор, тут можно привязаться к названию пункта меню

2021-10-30 13:16 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex2/DifferentElementsPageTest.java
> +            + "/label[@class='label-checkbox'][1]/child::text()/parent::label"));
//label[@class='label-checkbox'][1] - такого локатора более чем достаточно
Или так - .label-checkbox:nth-child(1)

2021-10-30 13:16 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex2/DifferentElementsPageTest.java
> +            + "/label[@class='label-checkbox'][3]/child::text()/parent::label"));
Аналогично упростить локатор

2021-10-30 13:16 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex2/DifferentElementsPageTest.java
> +            + "/label[@class='label-radio'][4]/child::text()/parent::label"));
Упростить локатор

2021-10-30 20:11 UTC, MaksimGudovich commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        softAssert.assertAll();
Не понял вопроса. softAssert.assertAll(); - это триггер всех софт проверок в тесте

2021-10-30 20:28 UTC, MaksimGudovich commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        softAssert.assertEquals("Home Page", webDriver.getTitle());
Но ведь необходимо проверить. что мы на домашней странице после переключений, поэтому в любом случае будет 2 одинаковых асерта. Я сделал изменения, но не уверен, что так лучше

2021-10-31 15:42 UTC, MaksimGudovich commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +                "Already have good base\n(about 20 internal and\nsome external projects),\nwish to get more…"));
Касательно этого и других аналогичных замечаний: не совсем понимаю зачем это делать, ведь эти данные используются только в одном месте. И во всех лекциях писались непосредственно в тесте. Я вынес, но мне не особо нравится появление промежуточных сущностей.

2021-11-01 12:55 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +                "Already have good base\n(about 20 internal and\nsome external projects),\nwish to get more…"));
Как правило данные выносят, особенно когда это большой текст. Сейчас у тебя несколько строк, а если нужно проверить 20 - 30 строк или большой текст но один раз...

2021-11-01 12:57 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        softAssert.assertEquals("Home Page", webDriver.getTitle());
Если в некольких местах присутствуют одинаковые проверки (идентичные), то лучше сделать на них метод иначе получается дублирование кода. И когда тайтл поменяется с 'Home Page' например на 'Your Home Page', то исправлять придется не в одном месте, а в некольких.

2021-11-01 13:04 UTC, Delnote approved these changes

2021-11-01 13:45 UTC, Delnote requested changes

2021-11-01 13:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        boolean isAllHeaderItemsDisplayed = headerElements.size() == 4;
Эта проверка вглядит очень странно, тут и далее более уместным будет assertEquals

2021-11-01 13:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        openHomePage();
Можно вынести в Before, этот метод есть в каждом тесте

2021-11-01 13:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
>          softAssert.assertTrue(hasIframe);
Данная проверка тут и далее не сработает, так как ты никогда не получишь сюда false. Из метода isElementExist придет либо true, либо он обвалится.

2021-11-01 13:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +    protected boolean isHomePage;
Наличие этой переменной избыточно, можно передавать isThisHomePage() сразу в ассерт. Можно переименовать просто в isHomePage()

2021-11-01 13:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        softAssert.assertAll();
Ок, просто не пользовался softAssert ранее. Уже посмотрел.

2021-11-02 08:06 UTC, Delnote approved these changes

2021-11-02 08:26 UTC, merged