Add homework 03
MaksimGudovich/MaksimGudovich pull request #3
Opened 2021-10-30 13:21 UTC by MaksimGudovich

2021-11-02 09:35 UTC, Delnote requested changes

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/util/ElementListHandler.java
> +        return wait.until(visibilityOfAllElements(elementList))
Можно выпилить этот wait. Его не нужно испльзовать везде, только там где он действительно нужен. И не нужно везде его явно передавать.

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/util/ElementListHandler.java
> +        ) {
Разметка

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/util/ElementListHandler.java
> +                break;
А что будет если такого элемента не найдется в списке? Тест пойдет дальше?

2021-11-02 09:35 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/BaseTest.java
> +    protected String userPassword;
Не надо так передавать userName и password. Нужен login метод.

2021-11-02 09:35 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/BaseTest.java
> +        }
Работу по пропертям вынести в utils

2021-11-02 09:35 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/DifferentElementsPageTest.java
> +        String title = new HomePage(webDriver)
Так с передачей дравера делать не надо. Сделай что-то вроде openHomePage()
И можно избавиться от создания каждый раз new Page()

2021-11-02 09:35 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/DifferentElementsPageTest.java
> +        new HomePage(webDriver).open().loginUser(userName, userPassword);
Если этот чейнинг используется много раз можно вынести это в отдельный метод.

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/HomePage.java
> +        return wait.until(visibilityOf(iframe)).isDisplayed();
Под капотом метод visibilityOf проверяет isDisplayed(). Так что тут избыточная проверка

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/HomePage.java
> +        webDriver = webDriver.switchTo().frame(iframe);
Какой смысл присвоения драйверу нового значения?

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +        return (T) this;
Какой смысл усложнять open(), если внутри захатдкожено открытие конкретного url?

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +    }
Аналогично комментарию к open()

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +public class AbstractPage<T> extends AbstractComponent {
Не понятная сущность. Все элементы должны лежать в своих педжах или глобальных элементах типо Menu

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +public class AbstractPage<T> extends AbstractComponent {
Не понятная сущность. Все элементы должны лежать в своих педжах или глобальных элементах типо HeaderMenu.

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +public class AbstractPage<T> extends AbstractComponent {
Не понятная сущность. Все элементы должны лежать в своих педжах или глобальных элементах типо Menu

2021-11-02 09:35 UTC, Delnote commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +        return leftMenu.isMenuElementDisplayed();
Этот метод, как и аналогичные не несет большой смысловой нагрузкию. Можно передавать leftMenu.isMenuElementDisplayed() сразу в ассерт.

2021-11-05 10:50 UTC, MaksimGudovich commented on src/main/java/com/epam/tc/hw3/page/AbstractPage.java
> +        return leftMenu.isMenuElementDisplayed();
Все таки считаю, что непосредственное обращение тестовых методов к компонентам страниц больше подходит void page object паттерну, а  в выполненном fluent page object паттерне будет не совсем правильно.

2021-11-08 08:45 UTC, Delnote requested changes

2021-11-08 08:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/JdiTestData.java
> +            .asList("Home", "Contact form", "Service", "Metals & Colors", "Elements packs");
Make all data as constants

2021-11-08 08:45 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/JdiTestData.java
> +        }
Create class FileUtils and move working with properties here.

2021-11-08 11:36 UTC, merged